export const indicatifTelList = [
    { value: "+1", label: "United States" },
    { value: "+44", label: "United Kingdom" },
    { value: "+33", label: "France" },
    { value: "+49", label: "Germany" },
    { value: "+34", label: "Spain" },
    { value: "+39", label: "Italy" },
    { value: "+81", label: "Japan" },
    { value: "+86", label: "China" },
    { value: "+91", label: "India" },
    { value: "+61", label: "Australia" },
    { value: "+55", label: "Brazil" },
    { value: "+7", label: "Russia" },
    { value: "+82", label: "South Korea" },
    { value: "+31", label: "Netherlands" },
    { value: "+46", label: "Sweden" },
    { value: "+41", label: "Switzerland" },
    { value: "+64", label: "New Zealand" },
    { value: "+351", label: "Portugal" },
    { value: "+48", label: "Poland" },
    { value: "+36", label: "Hungary" },
    { value: "+353", label: "Ireland" },
    { value: "+358", label: "Finland" },
    { value: "+420", label: "Czech Republic" },
    { value: "+386", label: "Slovenia" },
    { value: "+421", label: "Slovakia" },
    { value: "+370", label: "Lithuania" },
    { value: "+371", label: "Latvia" },
    { value: "+372", label: "Estonia" },
    { value: "+90", label: "Turkey" },
    { value: "+966", label: "Saudi Arabia" },
    { value: "+971", label: "United Arab Emirates" },
    { value: "+20", label: "Egypt" }, 
    { value: "+212", label: "Morocco" },
    { value: "+234", label: "Nigeria" },
    { value: "+254", label: "Kenya" },
    { value: "+27", label: "South Africa" },
    { value: "+60", label: "Malaysia" },
    { value: "+65", label: "Singapore" },
    { value: "+66", label: "Thailand" },
    { value: "+84", label: "Vietnam" },
    { value: "+95", label: "Myanmar" },    
    { value: "+880", label: "Bangladesh" },
    { value: "+977", label: "Nepal" },
    { value: "+94", label: "Sri Lanka" },
    { value: "+62", label: "Indonesia" },
    { value: "+63", label: "Philippines" },
    { value: "+52", label: "Mexico" },
    { value: "+54", label: "Argentina" },
    { value: "+56", label: "Chile" },
    { value: "+57", label: "Colombia" },
    { value: "+58", label: "Venezuela" },
    { value: "+507", label: "Panama" },
    { value: "+506", label: "Costa Rica" },
    { value: "+503", label: "El Salvador" },
    { value: "+502", label: "Guatemala" },
    { value: "+595", label: "Paraguay" },
    { value: "+598", label: "Uruguay" },
    { value: "+591", label: "Bolivia" },
    { value: "+593", label: "Ecuador" },   
    { value: "+974", label: "Qatar" },
    { value: "+965", label: "Kuwait" },
    { value: "+961", label: "Lebanon" },
    { value: "+962", label: "Jordan" },
    { value: "+963", label: "Syria" },
    { value: "+968", label: "Oman" },
];