export const cuisineList = [
  { label: 'American', value: 'american' },
  { label: 'BBQ', value: 'bbq' },
  { label: 'Breakfast', value: 'breakfast' },
  { label: 'Burgers', value: 'burgers' },
  { label: 'Cafe', value: 'cafe' },
  { label: 'Chinese', value: 'chinese' },
  { label: 'Desserts', value: 'desserts' },
  { label: 'French', value: 'french' },
  { label: 'Greek', value: 'greek' },
  { label: 'Healthy', value: 'healthy' },
  { label: 'Indian', value: 'indian' },
  { label: 'Italian', value: 'italian' },
  { label: 'Japanese', value: 'japanese' },
  { label: 'Mexican', value: 'mexican' },
  { label: 'Noodles', value: 'noodles' },
  { label: 'Organic', value: 'organic' },
  { label: 'Pasta', value: 'pasta' },
  { label: 'Pizza', value: 'pizza' },
  { label: 'Salads', value: 'salads' },
  { label: 'Seafood', value: 'seafood' },
  { label: 'Spanish', value: 'spanish' },
  { label: 'Steak', value: 'steak' },
  { label: 'Sushi', value: 'sushi' },
  { label: 'Tacos', value: 'tacos' },
  { label: 'Tapas', value: 'tapas' },
  { label: 'Vegan', value: 'vegan' },
];